using System.Net;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using Microsoft.AspNetCore.Mvc.Testing;
using UrlShortner.DTOs;
using UrlShortner.Models;
using Xunit;

namespace Test;

public class AliasAuthGuardTests : IClassFixture<WebApplicationFactory<Program>>
{
    private readonly WebApplicationFactory<Program> _factory;

    public AliasAuthGuardTests(WebApplicationFactory<Program> factory)
    {
        _factory = factory;
    }

    [Fact]
    public async Task CreateUrl_AnonymousUserWithAutoGenerated_ReturnsCreated()
    {
        // Arrange
        var client = _factory.CreateClient();
        var url = new Url
        {
            OriginalUrl = "https://example.com/anonymous",
            UserId = 1
        };

        // Act
        var response = await client.PostAsJsonAsync("/api/url", url);

        // Assert
        Assert.Equal(HttpStatusCode.Created, response.StatusCode);

        var createdUrl = await response.Content.ReadFromJsonAsync<Url>();
        Assert.NotNull(createdUrl);
        Assert.NotEmpty(createdUrl.ShortCode);
        Assert.Equal("https://example.com/anonymous", createdUrl.OriginalUrl);
    }

    [Fact]
    public async Task CreateUrl_AnonymousUserWithCustomAlias_Returns401Unauthorized()
    {
        // Arrange
        var client = _factory.CreateClient();
        var url = new Url
        {
            OriginalUrl = "https://example.com/custom",
            ShortCode = "myalias",
            UserId = 1
        };

        // Act
        var response = await client.PostAsJsonAsync("/api/url", url);

        // Assert
        Assert.Equal(HttpStatusCode.Unauthorized, response.StatusCode);

        var errorResponse = await response.Content.ReadFromJsonAsync<Dictionary<string, string>>();
        Assert.NotNull(errorResponse);
        Assert.Equal("AuthenticationRequired", errorResponse["error"]);
        Assert.Contains("Custom short codes", errorResponse["message"]);
        Assert.Contains("require authentication", errorResponse["message"]);
    }

    [Fact]
    public async Task CreateUrl_AuthenticatedUserWithCustomAlias_ReturnsCreated()
    {
        // Arrange - First register and login
        var client = _factory.CreateClient();
        var uniqueId = Guid.NewGuid().ToString("N").Substring(0, 8);
        var registerRequest = new RegisterRequest
        {
            Username = $"aliasuser_{uniqueId}",
            Email = $"alias_{uniqueId}@example.com",
            Password = "AliasPassword123!"
        };

        var registerResponse = await client.PostAsJsonAsync("/api/auth/register", registerRequest);
        var authResponse = await registerResponse.Content.ReadFromJsonAsync<AuthResponse>();

        // Add bearer token to client
        client.DefaultRequestHeaders.Authorization =
            new AuthenticationHeaderValue("Bearer", authResponse!.AccessToken);

        var url = new Url
        {
            OriginalUrl = "https://example.com/authenticated",
            ShortCode = $"custom{uniqueId}",
            UserId = authResponse.UserId
        };

        // Act
        var response = await client.PostAsJsonAsync("/api/url", url);

        // Assert
        Assert.Equal(HttpStatusCode.Created, response.StatusCode);

        var createdUrl = await response.Content.ReadFromJsonAsync<Url>();
        Assert.NotNull(createdUrl);
        Assert.Equal($"custom{uniqueId}", createdUrl.ShortCode);
        Assert.Equal("https://example.com/authenticated", createdUrl.OriginalUrl);
    }

    [Fact]
    public async Task CreateUrl_AuthenticatedUserWithAutoGenerated_ReturnsCreated()
    {
        // Arrange - Register and login
        var client = _factory.CreateClient();
        var uniqueId = Guid.NewGuid().ToString("N").Substring(0, 8);
        var registerRequest = new RegisterRequest
        {
            Username = $"authuser_{uniqueId}",
            Email = $"authuser_{uniqueId}@example.com",
            Password = "Password123!"
        };

        var registerResponse = await client.PostAsJsonAsync("/api/auth/register", registerRequest);
        var authResponse = await registerResponse.Content.ReadFromJsonAsync<AuthResponse>();

        client.DefaultRequestHeaders.Authorization =
            new AuthenticationHeaderValue("Bearer", authResponse!.AccessToken);

        var url = new Url
        {
            OriginalUrl = "https://example.com/auth-auto",
            UserId = authResponse.UserId
        };

        // Act
        var response = await client.PostAsJsonAsync("/api/url", url);

        // Assert
        Assert.Equal(HttpStatusCode.Created, response.StatusCode);

        var createdUrl = await response.Content.ReadFromJsonAsync<Url>();
        Assert.NotNull(createdUrl);
        Assert.NotEmpty(createdUrl.ShortCode);
    }
}
