using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using UrlShortner.API.Controllers;
using UrlShortner.API.Data;
using UrlShortner.Models;
using UrlShortner.API.Services;
using Xunit;

namespace Test;

public class UrlControllerTests
{
    private UrlShortnerDbContext GetInMemoryDbContext()
    {
        var options = new DbContextOptionsBuilder<UrlShortnerDbContext>()
            .UseInMemoryDatabase(databaseName: Guid.NewGuid().ToString())
            .Options;
        return new UrlShortnerDbContext(options);
    }

    private IShortCodeGenerator GetShortCodeGenerator()
    {
        return new ShortCodeGenerator();
    }

    [Fact]
    public async Task CreateReturns201CreatedWithAutoGeneratedShortCode()
    {
        using var context = GetInMemoryDbContext();
        var service = new UrlService(context, GetShortCodeGenerator(), new UrlValidator());
        var controller = new UrlController(service);

        var url = new Url
        {
            OriginalUrl = "https://facebook.com",
            UserId = 1,
            CreatedAt = DateTime.UtcNow
        };

        var result = await controller.Create(url);
        var createdResult = Assert.IsType<CreatedAtActionResult>(result);
        Assert.Equal(201, createdResult.StatusCode);

        var createdUrl = Assert.IsType<Url>(createdResult.Value);
        Assert.NotEmpty(createdUrl.ShortCode);
        Assert.Matches(@"^[0-9a-zA-Z]+$", createdUrl.ShortCode);
    }

    [Fact]
    public async Task CreateAutoGeneratesUniqueShortCodes()
    {
        using var context = GetInMemoryDbContext();
        var service = new UrlService(context, GetShortCodeGenerator(), new UrlValidator());
        var controller = new UrlController(service);

        var url1 = new Url
        {
            OriginalUrl = "https://example.com",
            UserId = 1,
            CreatedAt = DateTime.UtcNow
        };

        var url2 = new Url
        {
            OriginalUrl = "https://another.com",
            UserId = 1,
            CreatedAt = DateTime.UtcNow
        };

        var result1 = await controller.Create(url1);
        var result2 = await controller.Create(url2);

        var created1 = Assert.IsType<CreatedAtActionResult>(result1);
        var created2 = Assert.IsType<CreatedAtActionResult>(result2);

        var createdUrl1 = Assert.IsType<Url>(created1.Value);
        var createdUrl2 = Assert.IsType<Url>(created2.Value);

        Assert.NotEmpty(createdUrl1.ShortCode);
        Assert.NotEmpty(createdUrl2.ShortCode);
        Assert.NotEqual(createdUrl1.ShortCode, createdUrl2.ShortCode);
    }

    [Fact]
    public async Task CreateAutoGeneratesShortCodeWhenEmpty()
    {
        using var context = GetInMemoryDbContext();
        var service = new UrlService(context, GetShortCodeGenerator(), new UrlValidator());
        var controller = new UrlController(service);

        var url = new Url
        {
            OriginalUrl = "https://example.com",
            ShortCode = "",
            UserId = 1,
            CreatedAt = DateTime.UtcNow
        };

        var result = await controller.Create(url);

        var createdResult = Assert.IsType<CreatedAtActionResult>(result);
        var createdUrl = Assert.IsType<Url>(createdResult.Value);

        Assert.NotEmpty(createdUrl.ShortCode);
        Assert.Matches(@"^[0-9a-zA-Z]+$", createdUrl.ShortCode);
    }
}
